#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 02 17:46:08 EDT 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim pwm_generator_v1_0_tb_behav -key {Behavioral:sim_1:Functional:pwm_generator_v1_0_tb} -tclbatch pwm_generator_v1_0_tb.tcl -view /home/jizz/Documents/kv260-DPU-TDR/DPUCZDX8G/prj/Vivado/ip_repo/tb_pwm_generator_behav.wcfg -log simulate.log"
xsim pwm_generator_v1_0_tb_behav -key {Behavioral:sim_1:Functional:pwm_generator_v1_0_tb} -tclbatch pwm_generator_v1_0_tb.tcl -view /home/jizz/Documents/kv260-DPU-TDR/DPUCZDX8G/prj/Vivado/ip_repo/tb_pwm_generator_behav.wcfg -log simulate.log

