#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 30 14:40:19 EDT 2025
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim servo_generator_tb_behav -key {Behavioral:sim_1:Functional:servo_generator_tb} -tclbatch servo_generator_tb.tcl -view /home/jizz/Documents/kv260-DPU-TDR/DPUCZDX8G/prj/Vivado/ip_repo/servo_generator_tb_behav.wcfg -log simulate.log"
xsim servo_generator_tb_behav -key {Behavioral:sim_1:Functional:servo_generator_tb} -tclbatch servo_generator_tb.tcl -view /home/jizz/Documents/kv260-DPU-TDR/DPUCZDX8G/prj/Vivado/ip_repo/servo_generator_tb_behav.wcfg -log simulate.log

